---
stages:
    - lint

'pylint':
    stage: lint
    before_script:
        - yum install -y pylint python-inotify
    script:
        - for file in *.py ; do pylint $file ; done
    tags:
        - pylint
